---
- name: Prepare
  hosts: all
  tasks:
    - name: Initialize package cache
      ansible.builtin.package:
        update_cache: yes
        upgrade: yes
      become: yes
      # TODO: include emerge (from gentoo)
      when: ansible_facts['pkg_mgr'] in ['apt', 'pacman']
